name: coverage

on:
  push:
    branches: [main, develop]
    tags-ignore:
      - "*"
  pull_request:
    branches: [main, develop]
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Go test coverage
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - run: go test -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v4
