name: test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"
      - name: Test
        run: go test --race --shuffle on ./...
  coverage:
    runs-on: ubuntu-latest
    name: coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22"
      - run: go test -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v4
